# This workflow will update the README with the appropriate branch, when branched.

name: README

# Runs your workflow anytime someone creates a branch or tag,
# which triggers the create event. 
on:
  create:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: This branch
    # Github action to set environment variables that can be globally accessed between steps.
      uses: allenevans/set-env@v1.0.0
      with:
        BRANCH: $(git rev-parse --abbrev-ref HEAD) 

    - name: Printenv
      run: |
        echo "BRANCH=${BRANCH}"
        printenv
