# This workflow will update the README with the appropriate branch, when branched.
name: README
on:
  create:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set environmental values
      uses: allenevans/set-env@v1.0.0
      with:
        BRANCH: $(git rev-parse --abbrev-ref HEAD)
    - name: Create local changes
      run: |
        export BRANCH=$(git rev-parse --abbrev-ref HEAD) 
        export TRAVIS="Travis Build Status [![Build Status](https:\/\/travis-ci.com\/bioteam\/dictionaryutils.svg?branch=$BRANCH)](https:\/\/travis-ci.com\/github\/bioteam\/dictionaryutils\/branches)"
        export SCHEMA_URL="https:\/\/bms-gen3-dev.s3.amazonaws.com\/datadictionary\/$BRANCH\/schema.json"
        export SCHEMA="Dictionary Schema [schema.json]($SCHEMA_URL)"
        export VIZ="Dictionary Visualization [viz](https:\/\/bms-gen3-dev.s3.amazonaws.com\/datadictionary\/master\/viz\/index.html#$SCHEMA_URL)"
        sed -i "s/Travis Build Status.*/$TRAVIS/g" README.md
        sed -i "s/Dictionary Schema.*/$SCHEMA/g" README.md
        sed -i "s/Dictionary Visualization.*/$VIZ/g" README.md
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update README" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${BRANCH} 
     

